name: git-hygiene

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  git-hygiene:
    uses: saagpatel/sovereign/.github/workflows/git-hygiene.yml@188910981e3e9eb726002c33a335cfa15a42155c
