name: git-hygiene

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  git-hygiene:
    uses: saagpatel/sovereign/.github/workflows/git-hygiene.yml@3e2f0d5afc466a3b03ff94b62678d27ac7876ec9
