name: perf-enforced

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  perf-enforced:
    uses: saagpatel/sovereign/.github/workflows/perf-enforced.yml@9d06e14df760d39de22d4ed6868cf84bc604daa0
