name: perf-enforced

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  perf-enforced:
    uses: saagpatel/sovereign/.github/workflows/perf-enforced.yml@d20fe9e542f3efd545e0135dee4b4314b6af56a6
