name: perf-enforced

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  perf-enforced:
    uses: saagpatel/sovereign/.github/workflows/perf-enforced.yml@188910981e3e9eb726002c33a335cfa15a42155c
